/-
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2026 Konstantin Slutsky and contributors.
Developed with AI assistance; see ACKNOWLEDGEMENTS.md and AUTHORS.md.
-/

import RecurrentSections.RecurrenceSelection
import Mathlib.Topology.Sequences
import Mathlib.MeasureTheory.Constructions.BorelSpace.Metric

namespace RecurrentSections

open Set MeasureTheory

variable {Z : Type*} [MetricSpace Z]

def tailUnion (F : ℕ → Set Z) (N : ℕ) : Set Z := ⋃ n ≥ N, F n

def tailCluster (F : ℕ → Set Z) : Set Z := ⋂ N, closure (tailUnion F N)

theorem tailCluster_closed (F : ℕ → Set Z) : IsClosed (tailCluster F) :=
  isClosed_iInter fun _ => isClosed_closure

theorem tailCluster_mono {F H : ℕ → Set Z} (h : ∀ n, F n ⊆ H n) :
    tailCluster F ⊆ tailCluster H := by
  apply iInter_mono
  intro N
  apply closure_mono
  exact iUnion_mono fun n => iUnion_mono fun _ => h n

theorem mem_tailCluster_iff (F : ℕ → Set Z) (z : Z) :
    z ∈ tailCluster F ↔ ∀ ε : ℝ, 0 < ε → ∀ N : ℕ,
      ∃ n ≥ N, ∃ y ∈ F n, dist y z < ε := by
  simp only [tailCluster, mem_iInter, Metric.mem_closure_iff, tailUnion, mem_iUnion]
  constructor
  · intro h ε hε N
    obtain ⟨y, ⟨n, hn, hy⟩, hd⟩ := h N ε hε
    exact ⟨n, hn, y, hy, by simpa [dist_comm] using hd⟩
  · intro h N ε hε
    obtain ⟨n, hn, y, hy, hd⟩ := h ε hε N
    exact ⟨y, ⟨n, hn, hy⟩, by simpa [dist_comm] using hd⟩

theorem tailCluster_subset_closed (F : ℕ → Set Z) {B : Set Z}
    (hB : IsClosed B) (h : ∀ n, F n ⊆ B) : tailCluster F ⊆ B := by
  intro z hz
  have hz0 : z ∈ closure (tailUnion F 0) := mem_iInter.mp hz 0
  apply closure_minimal (s := tailUnion F 0) (t := B) ?_ hB hz0
  exact iUnion_subset fun n => iUnion_subset fun _ => h n

theorem tailCluster_nonempty [CompactSpace Z] (F : ℕ → Set Z)
    (hF : ∀ n, (F n).Nonempty) : (tailCluster F).Nonempty := by
  apply IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
  · intro N
    apply closure_mono
    exact iUnion_subset fun n => iUnion_subset fun hn =>
      subset_iUnion_of_subset n (subset_iUnion_of_subset (by omega : N ≤ n) subset_rfl)
  · intro N
    obtain ⟨z, hz⟩ := hF N
    exact ⟨z, subset_closure (mem_iUnion.mpr ⟨N, mem_iUnion.mpr ⟨le_rfl, hz⟩⟩)⟩
  · exact isClosed_closure.isCompact
  · intro N; exact isClosed_closure

theorem tailCluster_inter_nonempty [CompactSpace Z] (F : ℕ → Set Z)
    {B : Set Z} (hB : IsClosed B) (hF : ∀ n, (F n ∩ B).Nonempty) :
    (tailCluster F ∩ B).Nonempty := by
  obtain ⟨z, hz⟩ := tailCluster_nonempty (fun n => F n ∩ B) hF
  exact ⟨z, tailCluster_mono (fun _ => inter_subset_left) hz,
    tailCluster_subset_closed (fun n => F n ∩ B) hB (fun _ => inter_subset_right) hz⟩

/-- Countable-radius closure tests, useful for Borelness of return clusters. -/
theorem mem_closure_iff_nat (E : Set Z) (z : Z) :
    z ∈ closure E ↔ ∀ k : ℕ, ∃ y ∈ E, dist z y < 1 / ((k : ℝ) + 1) := by
  have h := Metric.mem_closure_range_iff_nat (e := fun y : E => (y : Z)) (a := z)
  simpa only [Subtype.range_coe_subtype, ofPred_mem_eq, Subtype.exists, exists_prop] using h

variable {X I : Type*} [MeasurableSpace X] [Countable I]
    [MeasurableSpace Z] [BorelSpace Z] [SecondCountableTopology Z]

/-- Borelness of a cluster relation generated by countably many fixed
points with Borel eligibility sets. This is proved from countable tests. -/
theorem measurableSet_tailCluster_graph (p : ℕ → I → Z) (B : ℕ → I → Set X)
    (hB : ∀ n i, MeasurableSet (B n i)) :
    MeasurableSet {xz : X × Z | xz.2 ∈ tailCluster
      (fun n => {z | ∃ i, xz.1 ∈ B n i ∧ p n i = z})} := by
  have heq : {xz : X × Z | xz.2 ∈ tailCluster
      (fun n => {z | ∃ i, xz.1 ∈ B n i ∧ p n i = z})} =
      ⋂ N : ℕ, ⋂ k : ℕ, ⋃ n : ℕ, ⋃ (_ : N ≤ n), ⋃ i : I,
        {xz : X × Z | xz.1 ∈ B n i ∧ dist xz.2 (p n i) < 1 / ((k : ℝ) + 1)} := by
    ext xz
    simp only [mem_ofPred_eq, tailCluster, mem_iInter, mem_closure_iff_nat,
      tailUnion, mem_iUnion]
    constructor
    · intro h N k
      obtain ⟨z, ⟨n, hn, i, hxi, rfl⟩, hd⟩ := h N k
      exact ⟨n, hn, i, hxi, hd⟩
    · intro h N k
      obtain ⟨n, hn, i, hxi, hd⟩ := h N k
      exact ⟨p n i, ⟨n, hn, i, hxi, rfl⟩, hd⟩
  rw [heq]
  exact MeasurableSet.iInter fun N => MeasurableSet.iInter fun k =>
    MeasurableSet.iUnion fun n => MeasurableSet.iUnion fun _ =>
      MeasurableSet.iUnion fun i =>
        ((hB n i).preimage measurable_fst).inter
          (measurableSet_lt (measurable_snd.dist measurable_const) measurable_const)

end RecurrentSections
