/-
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2026 Konstantin Slutsky and contributors.
Developed with AI assistance; see ACKNOWLEDGEMENTS.md and AUTHORS.md.
-/

import RecurrentSections

#print axioms RecurrentSections.polynomialGrowth_of_dilation_bound
#print axioms RecurrentSections.exists_adverse_scales
#print axioms RecurrentSections.measure_neighborhood_le
#print axioms RecurrentSections.polynomialGrowth_of_recurrent
#print axioms RecurrentSections.polynomialGrowth_of_recurrent_with_lowerBounds
#print axioms RecurrentSections.virtuallyNilpotent_of_universalRecurrence
#print axioms RecurrentSections.recursAt_smul
#print axioms RecurrentSections.recursAt_finite_union
#print axioms RecurrentSections.measurableSet_tailCluster_graph
#print axioms RecurrentSections.returnCluster_nonempty
#print axioms RecurrentSections.returnCluster_smul
#print axioms RecurrentSections.recentered_multiplicity
#print axioms RecurrentSections.recentered_recurrent
#print axioms RecurrentSections.finite_color_assembly
#print axioms RecurrentSections.universalRecurrence_of_polynomialGrowth
#print axioms RecurrentSections.universalRecurrence_of_virtuallyNilpotent
#print axioms RecurrentSections.recurrence_iff_virtuallyNilpotent
#print axioms RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent
#print axioms RecurrentSections.WordGeometry.tendsto_growthEntropy
#print axioms RecurrentSections.WordGeometry.exp_growthEntropy_le_volume
#print axioms RecurrentSections.measure_neighborhood_le_of_separated
#print axioms RecurrentSections.not_recurrent_of_summable_ratios
#print axioms RecurrentSections.exponential_ratio_bound
#print axioms RecurrentSections.not_recurrent_of_exponential_bounds
#print axioms RecurrentSections.subexponentialGrowth_of_one_recurrent_sequence
#print axioms RecurrentSections.subexponentialGrowth_of_universalFreeSomeRecurrence

#check RecurrentSections.polynomialGrowth_of_recurrent
#check RecurrentSections.virtuallyNilpotent_of_universalRecurrence
#check RecurrentSections.universalRecurrence_of_polynomialGrowth
#check RecurrentSections.universalRecurrence_of_virtuallyNilpotent
#check RecurrentSections.recurrence_iff_virtuallyNilpotent
#check RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent
#check RecurrentSections.not_recurrent_of_summable_ratios
#check RecurrentSections.subexponentialGrowth_of_one_recurrent_sequence
#check RecurrentSections.subexponentialGrowth_of_some_recurrent_sections
#check RecurrentSections.subexponentialGrowth_of_universalFreeSomeRecurrence
#print RecurrentSections.SubexponentialGrowth
#print RecurrentSections.HasSomeRecurrentSections
#print RecurrentSections.UniversalFreeSomeRecurrence
#print RecurrentSections.PolynomialGeometry
#print RecurrentSections.StandardBorelTools
#print RecurrentSections.CompactChoice

-- Newly proved geometry and reusable descriptive-set-theoretic tools.
#print axioms RecurrentSections.card_mul_volume_le
#print axioms RecurrentSections.groupPacking_of_doubling
#print axioms RecurrentSections.scaledBall_cover
#print axioms RecurrentSections.scaledModels_of_doubling
#print axioms RecurrentSections.polynomialGeometry_of_standard_theorems
#print axioms BorelToolkit.exists_countable_independent_cover
#print axioms BorelToolkit.exists_maximal_extension
#print axioms BorelToolkit.exists_finite_independent_cover
#print axioms BorelToolkit.exists_finite_minimizer
#print axioms BorelToolkit.closedSelector_mem
#print axioms BorelToolkit.measurable_closedSelector
#print axioms BorelToolkit.weaklyMeasurable_of_compact_graph
#print axioms RecurrentSections.borelExtension
#print axioms RecurrentSections.borelColoring
#print axioms RecurrentSections.standardBorelTools
#print axioms RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent_of_standard_theorems

#check BorelToolkit.exists_maximal_extension
#check BorelToolkit.exists_finite_independent_cover
#check BorelToolkit.exists_finite_minimizer
#check BorelToolkit.exists_measurable_selection
#check RecurrentSections.polynomialGeometry_of_standard_theorems
#check RecurrentSections.standardBorelTools
#check RecurrentSections.recurrence_iff_polynomialGrowth_of_standard_theorems
#check RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent_of_standard_theorems
#print RecurrentSections.PolynomialVolumeTheorem
#print MetricGeometry.CommonCompactEmbeddingTheorem
#print BorelToolkit.CompactSectionProjectionTheorem
#print BorelToolkit.MeasurableNeighborhoods
#print BorelToolkit.WeaklyMeasurable

-- Common compact embedding and compact-section projection are now proved.
#print axioms MetricGeometry.commonCompactEmbeddingTheorem
#print axioms MetricGeometry.exists_common_compact_embedding
#print axioms BorelToolkit.analytic_countable_separation
#print axioms BorelToolkit.exists_borel_open_rectangles
#print axioms BorelToolkit.measurableSet_proj_of_compact_sections
#print axioms BorelToolkit.compactSectionProjectionTheorem
#print axioms RecurrentSections.universalRecurrence_of_volumeDoubling
#check MetricGeometry.commonCompactEmbeddingTheorem
#check MetricGeometry.exists_common_compact_embedding
#check BorelToolkit.analytic_countable_separation
#check BorelToolkit.exists_borel_open_rectangles
#check BorelToolkit.compactSectionProjectionTheorem
#check BorelToolkit.measurableSet_proj_of_compact_sections
#check RecurrentSections.universalRecurrence_of_volumeDoubling

-- Expand all remaining mathematical inputs and the main property.
#print RecurrentSections.FreePmpModel
#print RecurrentSections.PolynomialGrowth
#print RecurrentSections.TwoSidedPolynomialGrowth
#print RecurrentSections.WordGeometry
#print RecurrentSections.UniversalMaximalRecurrence
#print RecurrentSections.HasRecurrentMaximalSections

-- The free pmp test action and its reusable measure-theoretic ingredients are proved.
#print axioms BorelToolkit.measurePreserving_restrict_conull
#check BorelToolkit.measurePreserving_restrict_conull
#print axioms BorelToolkit.infinitePi_ae_ne
#check BorelToolkit.infinitePi_ae_ne
#print axioms BorelToolkit.infinitePi_ae_injective
#check BorelToolkit.infinitePi_ae_injective
#print axioms BorelToolkit.Bernoulli.measurableSet_freePart
#check BorelToolkit.Bernoulli.measurableSet_freePart
#print axioms BorelToolkit.Bernoulli.ae_freePart
#check BorelToolkit.Bernoulli.ae_freePart
#print axioms BorelToolkit.Bernoulli.measurePreserving_shift
#check BorelToolkit.Bernoulli.measurePreserving_shift
#print axioms BorelToolkit.Bernoulli.free
#check BorelToolkit.Bernoulli.free
#print axioms RecurrentSections.nonempty_freePmpModel
#check RecurrentSections.nonempty_freePmpModel
#print axioms RecurrentSections.polynomialGrowth_of_universalRecurrence
#check RecurrentSections.polynomialGrowth_of_universalRecurrence
#print BorelToolkit.Bernoulli.freePart
#print BorelToolkit.Bernoulli.FreeSpace
#print BorelToolkit.Bernoulli.freeMeasure

-- Partial polynomial-volume formalization on the research branch.
#print axioms RecurrentSections.twoSidedPolynomialGrowth_of_tendsto_ratio
#check RecurrentSections.twoSidedPolynomialGrowth_of_tendsto_ratio
#print axioms RecurrentSections.polynomialVolumeTheorem_of_finite
#check RecurrentSections.polynomialVolumeTheorem_of_finite
#print axioms RecurrentSections.universalRecurrence_of_finite
#check RecurrentSections.universalRecurrence_of_finite

#check RecurrentSections.WordGeometry.nonempty_ofFG
#print axioms RecurrentSections.WordGeometry.nonempty_ofFG

#check RecurrentSections.WordGeometry.exists_length_map_le
#print axioms RecurrentSections.WordGeometry.exists_length_map_le

#check RecurrentSections.WordGeometry.exists_volume_le_subgroup
#print axioms RecurrentSections.WordGeometry.exists_volume_le_subgroup

#check RecurrentSections.TwoSidedPolynomialGrowth.of_comparison
#print axioms RecurrentSections.TwoSidedPolynomialGrowth.of_comparison

#check RecurrentSections.polynomialGrowth_iff_subgroup
#print axioms RecurrentSections.polynomialGrowth_iff_subgroup

#check RecurrentSections.twoSidedPolynomialGrowth_iff_subgroup
#print axioms RecurrentSections.twoSidedPolynomialGrowth_iff_subgroup

#check RecurrentSections.twoSidedPolynomialGrowth_iff_wordGeometry
#print axioms RecurrentSections.twoSidedPolynomialGrowth_iff_wordGeometry

#check RecurrentSections.virtuallyNilpotent_of_polynomialGrowth
#print axioms RecurrentSections.virtuallyNilpotent_of_polynomialGrowth
#check RecurrentSections.virtuallyNilpotent_of_recurrent
#print axioms RecurrentSections.virtuallyNilpotent_of_recurrent

#check RecurrentSections.twoSidedPolynomialGrowth_of_virtuallyNilpotent
#print axioms RecurrentSections.twoSidedPolynomialGrowth_of_virtuallyNilpotent


#check RecurrentSections.polynomialVolumeTheorem_of_nilpotent_volume
#print axioms RecurrentSections.polynomialVolumeTheorem_of_nilpotent_volume

#check RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent_of_nilpotent_volume
#print axioms RecurrentSections.maximalRecurrence_iff_virtuallyNilpotent_of_nilpotent_volume

-- Exact free-abelian balls and the general abelian base case.
#check RecurrentSections.FreeAbelianGeometry.volume_wordGeometry
#print axioms RecurrentSections.FreeAbelianGeometry.volume_wordGeometry
#check RecurrentSections.twoSidedPolynomialGrowth_iff_mulEquiv
#print axioms RecurrentSections.twoSidedPolynomialGrowth_iff_mulEquiv
#check RecurrentSections.twoSidedPolynomialGrowth_of_commGroup
#print axioms RecurrentSections.twoSidedPolynomialGrowth_of_commGroup

-- Polynomial upper bounds and the full Gromov equivalence are now proved.
#check RecurrentSections.exists_conjugation_bound_of_upperCentralSeries
#print axioms RecurrentSections.exists_conjugation_bound_of_upperCentralSeries
#check RecurrentSections.WordSwaps.exists_steps_of_perm
#print axioms RecurrentSections.WordSwaps.exists_steps_of_perm
#check RecurrentSections.volume_le_of_swap_bound
#print axioms RecurrentSections.volume_le_of_swap_bound
#check RecurrentSections.polynomialGrowth_of_nilpotent
#print axioms RecurrentSections.polynomialGrowth_of_nilpotent
#check RecurrentSections.polynomialGrowth_of_virtuallyNilpotent
#print axioms RecurrentSections.polynomialGrowth_of_virtuallyNilpotent
#check RecurrentSections.polynomialGrowth_iff_virtuallyNilpotent
#print axioms RecurrentSections.polynomialGrowth_iff_virtuallyNilpotent

-- Quotient geometry and last-term compression; no sharp distortion is assumed here.
#print axioms RecurrentSections.lowerCentralSeries_commutator_le
#print axioms RecurrentSections.WordGeometry.map_volume_mul_kernelVolume_le
#print axioms RecurrentSections.WordGeometry.volume_le_map_volume_mul_kernelVolume
#print axioms RecurrentSections.powerCompression_commutator
#print axioms RecurrentSections.powerCompression_of_last_lowerCentralSeries
#print axioms RecurrentSections.exists_ball_compression_of_commGroup
#print axioms RecurrentSections.exists_last_lowerCentralSeries_ball_inclusion

-- Complete matching-volume proof and the characterizations with no unproved inputs.
#check RecurrentSections.exists_finite_positive_relations
#print axioms RecurrentSections.exists_finite_positive_relations
#print axioms RecurrentSections.exists_weighted_conjugation_bound
#print axioms RecurrentSections.exists_weighted_elimination
#print axioms RecurrentSections.exists_weighted_collection
#check RecurrentSections.exists_last_lowerCentralSeries_distortion_bound
#print axioms RecurrentSections.exists_last_lowerCentralSeries_distortion_bound
#check RecurrentSections.twoSidedPolynomialGrowth_of_normal_subgroup_distortion
#print axioms RecurrentSections.twoSidedPolynomialGrowth_of_normal_subgroup_distortion
#check RecurrentSections.twoSidedPolynomialGrowth_of_nilpotent
#print axioms RecurrentSections.twoSidedPolynomialGrowth_of_nilpotent
#check RecurrentSections.nilpotentPolynomialVolumeTheorem
#print axioms RecurrentSections.nilpotentPolynomialVolumeTheorem
#check RecurrentSections.polynomialVolumeTheorem
#print axioms RecurrentSections.polynomialVolumeTheorem
#check RecurrentSections.recurrence_iff_virtuallyNilpotent_of_standard_theorems
#print axioms RecurrentSections.recurrence_iff_virtuallyNilpotent_of_standard_theorems
#check RecurrentSections.freeRecurrence_iff_virtuallyNilpotent_of_standard_theorems
#print axioms RecurrentSections.freeRecurrence_iff_virtuallyNilpotent_of_standard_theorems
