/-
SPDX-License-Identifier: Apache-2.0
Copyright (c) 2026 Konstantin Slutsky and contributors.
Developed with AI assistance; see ACKNOWLEDGEMENTS.md and AUTHORS.md.
-/

import BorelToolkit.Graph
import Mathlib.MeasureTheory.Group.Action

/-! # Graphs generated by finitely many action maps

The acting group need not be countable and the action need not be free.
Only a finite inverse-closed set of group elements is used.
-/

namespace BorelToolkit

open Set MeasurableSpace

variable {G X : Type*} [Group G] [MulAction G X]

/-- The simple graph generated by a finite inverse-closed family of
action maps. Fixed points do not create loops. -/
def finiteActionGraph (F : Finset G) (hF : ∀ g ∈ F, g⁻¹ ∈ F) : SimpleGraph X where
  Adj x y := x ≠ y ∧ ∃ g ∈ F, g • x = y
  symm := ⟨by
    rintro x y ⟨hne, g, hg, hxy⟩
    exact ⟨hne.symm, g⁻¹, hF g hg, by rw [← hxy, inv_smul_smul]⟩⟩
  loopless := ⟨fun _ h => h.1 rfl⟩

theorem finiteActionGraph_finite (F : Finset G) (hF : ∀ g ∈ F, g⁻¹ ∈ F) (x : X) :
    ((finiteActionGraph F hF).neighborSet x).Finite := by
  apply ((F : Set G).toFinite.image (fun g => g • x)).subset
  rintro y ⟨_, g, hg, hxy⟩
  exact ⟨g, hg, hxy⟩

/-- Measurability of the graph-neighborhood operation follows directly
from the finite family of measurable maps, including actions with stabilizers. -/
theorem finiteActionGraph_measurable [MeasurableSpace X] [CountablySeparated X]
    [MeasurableConstSMul G X] (F : Finset G) (hF : ∀ g ∈ F, g⁻¹ ∈ F) :
    MeasurableNeighborhoods (finiteActionGraph (X := X) F hF) := by
  intro S hS
  have heq : neighbors (finiteActionGraph (X := X) F hF) S =
      ⋃ g ∈ F, {x | x ≠ g • x} ∩ ((fun x : X => g • x) ⁻¹' S) := by
    ext x
    constructor
    · rintro ⟨y, hy, hne, g, hg, hxy⟩
      exact mem_iUnion.mpr ⟨g, mem_iUnion.mpr ⟨hg, by simpa [hxy] using And.intro hne hy⟩⟩
    · intro hx
      obtain ⟨g, hg, hne, hs⟩ := mem_iUnion₂.mp hx
      exact ⟨g • x, hs, hne, g, hg, rfl⟩
  rw [heq]
  apply MeasurableSet.biUnion (Finset.countable_toSet F)
  intro g _
  obtain ⟨f, hfm, hfi⟩ := measurable_injection_nat_bool_of_countablySeparated X
  have hfixed : MeasurableSet {x : X | x = g • x} := by
    simpa only [Function.comp_apply, hfi.eq_iff] using
      measurableSet_eq_fun hfm (hfm.comp (measurable_const_smul g))
  exact hfixed.compl.inter ((measurable_const_smul g) hS)

end BorelToolkit
